{% set name = "antitesting" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/antitesting-{{ version }}.tar.gz
  sha256: 4b65d9c437727ab705e66b5704731bc1cddf788b4b6a380c73fe8a78b7ff9815

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - antitesting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/antitesting
  summary: A Pytest plugin that allows you to describe disabled tests in one or more files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
