{% set name = "antitesting" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/antitesting-{{ version }}.tar.gz
  sha256: 5d175436f9d2b918a3f005c97869cc6a3f6be6b1dfcc76a526bf660a100ca85d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - antitesting
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/antitesting
  summary: A Pytest plugin that allows you to describe disabled tests in one or more files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
